name: abo-analysis-env
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - bioconda::fastqc=0.12.1
  - bioconda::bwa=0.7.17
  - conda-forge::ncurses
  - bioconda::samtools=1.19.2
  - bioconda::minimap2=2.26
  - conda-forge::biopython=1.83
  - python=3.10
  - pip
  - pip:
    - numpy==1.26.4
    - Bio==1.6.2
    - openpyxl==3.1.2
    - pandas==2.2.0
    - pysam==0.22.0
    - matplotlib==3.8.2
    - xlsxwriter==3.1.9
    - multiqc==1.18
